#!/bin/bash
ETEOL=$(tput el)
tput sc

clear
echo "--------------------"
echo "Watchdog"
echo "--------------------"
DOCKER=0
if [ "$1" -eq 1 ]
then
    sudo docker kill --signal=SIGINT $(sudo docker ps -qaf "status=running") > /dev/null
    TRIP=1
    echo 1 > TRIP
    else 
    echo 0 > TRIP
fi


while true
do 
    TRIP=$(cat TRIP)
        DISK=$(df -h / | awk 'NR==2 {print $5}' | tr -d '%')
    DOCKERDSK=$(sudo du -sb /var/lib/docker/containers | awk '{print $1}')
    DOCKERDSKFRM=$(numfmt --to iec --format "%8.4f" $DOCKERDSK)
    CONTUPD=$(sudo docker ps -qaf "status=running" | wc -l)
    tput rc
    if [ $DISK -gt 75 ]
    then
        if [ $TRIP -eq 0 ]
        then
            sudo docker kill --signal=SIGINT $(sudo docker ps -qaf "status=running") > /dev/null
            TRIP=1
            echo 1 > TRIP
        fi


    elif [ $TRIP -eq 1 ]
        then
            if [ $CONTUPD -eq 0 ]
                then
                printf "Rebooting!\033[0K\r\n"
                echo 0 > TRIP
                pm2 stop all
                sudo reboot
              exit 1
            else 
                if [ $DOCKER -eq 5 ]; then
                   DOCKER=0
                   sudo docker rm -v -f $(sudo docker ps -qaf "status=exited") > /dev/null
                else
                   DOCKER=$((DOCKER+1))
                   
               fi
               sleep 1
                
                printf "Pending reboot. $DISK/75$ETEOL\033[0K\r\n"
            fi
    else
        printf "Guarding.$ETEOL\033[0K\r\n"
    fi
    sleep 1
done